name: Deploy to VPS

on:
  push:
    branches: [main]  # change to your deployment branch
  workflow_dispatch:  # allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/debian/cycling-web/cycling-website
            git pull origin main
            source ../venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart cycling-app